/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardMetricRouteImport } from './routes/dashboard/metric'
import { Route as DashboardDomainRouteImport } from './routes/dashboard/domain'
import { Route as DashboardDatabasesRouteImport } from './routes/dashboard/databases'
import { Route as DashboardApplicationWeatherRouteImport } from './routes/dashboard/application/weather'
import { Route as DashboardApplicationTourismRouteImport } from './routes/dashboard/application/tourism'
import { Route as DashboardApplicationTodoRouteImport } from './routes/dashboard/application/todo'
import { Route as DashboardApplicationSocialAppRouteImport } from './routes/dashboard/application/social-app'
import { Route as DashboardApplicationFileManagerRouteImport } from './routes/dashboard/application/file-manager'
import { Route as DashboardApplicationContactRouteImport } from './routes/dashboard/application/contact'
import { Route as DashboardApplicationChatAppRouteImport } from './routes/dashboard/application/chat-app'
import { Route as DashboardApplicationCalenderRouteImport } from './routes/dashboard/application/calender'
import { Route as DashboardApplicationBlogRouteImport } from './routes/dashboard/application/blog'
import { Route as DashboardAccountSettingsRouteImport } from './routes/dashboard/account/settings'
import { Route as DashboardAccountInvoiceRouteImport } from './routes/dashboard/account/invoice'
import { Route as DashboardAccountCreateInvoiceRouteImport } from './routes/dashboard/account/create-invoice'
import { Route as DashboardAccountBillingRouteImport } from './routes/dashboard/account/billing'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMetricRoute = DashboardMetricRouteImport.update({
  id: '/metric',
  path: '/metric',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDomainRoute = DashboardDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDatabasesRoute = DashboardDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApplicationWeatherRoute =
  DashboardApplicationWeatherRouteImport.update({
    id: '/application/weather',
    path: '/application/weather',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationTourismRoute =
  DashboardApplicationTourismRouteImport.update({
    id: '/application/tourism',
    path: '/application/tourism',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationTodoRoute =
  DashboardApplicationTodoRouteImport.update({
    id: '/application/todo',
    path: '/application/todo',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationSocialAppRoute =
  DashboardApplicationSocialAppRouteImport.update({
    id: '/application/social-app',
    path: '/application/social-app',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationFileManagerRoute =
  DashboardApplicationFileManagerRouteImport.update({
    id: '/application/file-manager',
    path: '/application/file-manager',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationContactRoute =
  DashboardApplicationContactRouteImport.update({
    id: '/application/contact',
    path: '/application/contact',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationChatAppRoute =
  DashboardApplicationChatAppRouteImport.update({
    id: '/application/chat-app',
    path: '/application/chat-app',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationCalenderRoute =
  DashboardApplicationCalenderRouteImport.update({
    id: '/application/calender',
    path: '/application/calender',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardApplicationBlogRoute =
  DashboardApplicationBlogRouteImport.update({
    id: '/application/blog',
    path: '/application/blog',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountSettingsRoute =
  DashboardAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountInvoiceRoute = DashboardAccountInvoiceRouteImport.update({
  id: '/account/invoice',
  path: '/account/invoice',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountCreateInvoiceRoute =
  DashboardAccountCreateInvoiceRouteImport.update({
    id: '/account/create-invoice',
    path: '/account/create-invoice',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountBillingRoute = DashboardAccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/domain': typeof DashboardDomainRoute
  '/dashboard/metric': typeof DashboardMetricRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/billing': typeof DashboardAccountBillingRoute
  '/dashboard/account/create-invoice': typeof DashboardAccountCreateInvoiceRoute
  '/dashboard/account/invoice': typeof DashboardAccountInvoiceRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/dashboard/application/blog': typeof DashboardApplicationBlogRoute
  '/dashboard/application/calender': typeof DashboardApplicationCalenderRoute
  '/dashboard/application/chat-app': typeof DashboardApplicationChatAppRoute
  '/dashboard/application/contact': typeof DashboardApplicationContactRoute
  '/dashboard/application/file-manager': typeof DashboardApplicationFileManagerRoute
  '/dashboard/application/social-app': typeof DashboardApplicationSocialAppRoute
  '/dashboard/application/todo': typeof DashboardApplicationTodoRoute
  '/dashboard/application/tourism': typeof DashboardApplicationTourismRoute
  '/dashboard/application/weather': typeof DashboardApplicationWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/domain': typeof DashboardDomainRoute
  '/dashboard/metric': typeof DashboardMetricRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/billing': typeof DashboardAccountBillingRoute
  '/dashboard/account/create-invoice': typeof DashboardAccountCreateInvoiceRoute
  '/dashboard/account/invoice': typeof DashboardAccountInvoiceRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/dashboard/application/blog': typeof DashboardApplicationBlogRoute
  '/dashboard/application/calender': typeof DashboardApplicationCalenderRoute
  '/dashboard/application/chat-app': typeof DashboardApplicationChatAppRoute
  '/dashboard/application/contact': typeof DashboardApplicationContactRoute
  '/dashboard/application/file-manager': typeof DashboardApplicationFileManagerRoute
  '/dashboard/application/social-app': typeof DashboardApplicationSocialAppRoute
  '/dashboard/application/todo': typeof DashboardApplicationTodoRoute
  '/dashboard/application/tourism': typeof DashboardApplicationTourismRoute
  '/dashboard/application/weather': typeof DashboardApplicationWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/dashboard/databases': typeof DashboardDatabasesRoute
  '/dashboard/domain': typeof DashboardDomainRoute
  '/dashboard/metric': typeof DashboardMetricRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/billing': typeof DashboardAccountBillingRoute
  '/dashboard/account/create-invoice': typeof DashboardAccountCreateInvoiceRoute
  '/dashboard/account/invoice': typeof DashboardAccountInvoiceRoute
  '/dashboard/account/settings': typeof DashboardAccountSettingsRoute
  '/dashboard/application/blog': typeof DashboardApplicationBlogRoute
  '/dashboard/application/calender': typeof DashboardApplicationCalenderRoute
  '/dashboard/application/chat-app': typeof DashboardApplicationChatAppRoute
  '/dashboard/application/contact': typeof DashboardApplicationContactRoute
  '/dashboard/application/file-manager': typeof DashboardApplicationFileManagerRoute
  '/dashboard/application/social-app': typeof DashboardApplicationSocialAppRoute
  '/dashboard/application/todo': typeof DashboardApplicationTodoRoute
  '/dashboard/application/tourism': typeof DashboardApplicationTourismRoute
  '/dashboard/application/weather': typeof DashboardApplicationWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/databases'
    | '/dashboard/domain'
    | '/dashboard/metric'
    | '/dashboard/security'
    | '/dashboard/'
    | '/dashboard/account/billing'
    | '/dashboard/account/create-invoice'
    | '/dashboard/account/invoice'
    | '/dashboard/account/settings'
    | '/dashboard/application/blog'
    | '/dashboard/application/calender'
    | '/dashboard/application/chat-app'
    | '/dashboard/application/contact'
    | '/dashboard/application/file-manager'
    | '/dashboard/application/social-app'
    | '/dashboard/application/todo'
    | '/dashboard/application/tourism'
    | '/dashboard/application/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/databases'
    | '/dashboard/domain'
    | '/dashboard/metric'
    | '/dashboard/security'
    | '/dashboard'
    | '/dashboard/account/billing'
    | '/dashboard/account/create-invoice'
    | '/dashboard/account/invoice'
    | '/dashboard/account/settings'
    | '/dashboard/application/blog'
    | '/dashboard/application/calender'
    | '/dashboard/application/chat-app'
    | '/dashboard/application/contact'
    | '/dashboard/application/file-manager'
    | '/dashboard/application/social-app'
    | '/dashboard/application/todo'
    | '/dashboard/application/tourism'
    | '/dashboard/application/weather'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/databases'
    | '/dashboard/domain'
    | '/dashboard/metric'
    | '/dashboard/security'
    | '/dashboard/'
    | '/dashboard/account/billing'
    | '/dashboard/account/create-invoice'
    | '/dashboard/account/invoice'
    | '/dashboard/account/settings'
    | '/dashboard/application/blog'
    | '/dashboard/application/calender'
    | '/dashboard/application/chat-app'
    | '/dashboard/application/contact'
    | '/dashboard/application/file-manager'
    | '/dashboard/application/social-app'
    | '/dashboard/application/todo'
    | '/dashboard/application/tourism'
    | '/dashboard/application/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/metric': {
      id: '/dashboard/metric'
      path: '/metric'
      fullPath: '/dashboard/metric'
      preLoaderRoute: typeof DashboardMetricRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/domain': {
      id: '/dashboard/domain'
      path: '/domain'
      fullPath: '/dashboard/domain'
      preLoaderRoute: typeof DashboardDomainRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/databases': {
      id: '/dashboard/databases'
      path: '/databases'
      fullPath: '/dashboard/databases'
      preLoaderRoute: typeof DashboardDatabasesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/weather': {
      id: '/dashboard/application/weather'
      path: '/application/weather'
      fullPath: '/dashboard/application/weather'
      preLoaderRoute: typeof DashboardApplicationWeatherRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/tourism': {
      id: '/dashboard/application/tourism'
      path: '/application/tourism'
      fullPath: '/dashboard/application/tourism'
      preLoaderRoute: typeof DashboardApplicationTourismRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/todo': {
      id: '/dashboard/application/todo'
      path: '/application/todo'
      fullPath: '/dashboard/application/todo'
      preLoaderRoute: typeof DashboardApplicationTodoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/social-app': {
      id: '/dashboard/application/social-app'
      path: '/application/social-app'
      fullPath: '/dashboard/application/social-app'
      preLoaderRoute: typeof DashboardApplicationSocialAppRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/file-manager': {
      id: '/dashboard/application/file-manager'
      path: '/application/file-manager'
      fullPath: '/dashboard/application/file-manager'
      preLoaderRoute: typeof DashboardApplicationFileManagerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/contact': {
      id: '/dashboard/application/contact'
      path: '/application/contact'
      fullPath: '/dashboard/application/contact'
      preLoaderRoute: typeof DashboardApplicationContactRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/chat-app': {
      id: '/dashboard/application/chat-app'
      path: '/application/chat-app'
      fullPath: '/dashboard/application/chat-app'
      preLoaderRoute: typeof DashboardApplicationChatAppRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/calender': {
      id: '/dashboard/application/calender'
      path: '/application/calender'
      fullPath: '/dashboard/application/calender'
      preLoaderRoute: typeof DashboardApplicationCalenderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/application/blog': {
      id: '/dashboard/application/blog'
      path: '/application/blog'
      fullPath: '/dashboard/application/blog'
      preLoaderRoute: typeof DashboardApplicationBlogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/settings': {
      id: '/dashboard/account/settings'
      path: '/account/settings'
      fullPath: '/dashboard/account/settings'
      preLoaderRoute: typeof DashboardAccountSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/invoice': {
      id: '/dashboard/account/invoice'
      path: '/account/invoice'
      fullPath: '/dashboard/account/invoice'
      preLoaderRoute: typeof DashboardAccountInvoiceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/create-invoice': {
      id: '/dashboard/account/create-invoice'
      path: '/account/create-invoice'
      fullPath: '/dashboard/account/create-invoice'
      preLoaderRoute: typeof DashboardAccountCreateInvoiceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/billing': {
      id: '/dashboard/account/billing'
      path: '/account/billing'
      fullPath: '/dashboard/account/billing'
      preLoaderRoute: typeof DashboardAccountBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDatabasesRoute: typeof DashboardDatabasesRoute
  DashboardDomainRoute: typeof DashboardDomainRoute
  DashboardMetricRoute: typeof DashboardMetricRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountBillingRoute: typeof DashboardAccountBillingRoute
  DashboardAccountCreateInvoiceRoute: typeof DashboardAccountCreateInvoiceRoute
  DashboardAccountInvoiceRoute: typeof DashboardAccountInvoiceRoute
  DashboardAccountSettingsRoute: typeof DashboardAccountSettingsRoute
  DashboardApplicationBlogRoute: typeof DashboardApplicationBlogRoute
  DashboardApplicationCalenderRoute: typeof DashboardApplicationCalenderRoute
  DashboardApplicationChatAppRoute: typeof DashboardApplicationChatAppRoute
  DashboardApplicationContactRoute: typeof DashboardApplicationContactRoute
  DashboardApplicationFileManagerRoute: typeof DashboardApplicationFileManagerRoute
  DashboardApplicationSocialAppRoute: typeof DashboardApplicationSocialAppRoute
  DashboardApplicationTodoRoute: typeof DashboardApplicationTodoRoute
  DashboardApplicationTourismRoute: typeof DashboardApplicationTourismRoute
  DashboardApplicationWeatherRoute: typeof DashboardApplicationWeatherRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDatabasesRoute: DashboardDatabasesRoute,
  DashboardDomainRoute: DashboardDomainRoute,
  DashboardMetricRoute: DashboardMetricRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountBillingRoute: DashboardAccountBillingRoute,
  DashboardAccountCreateInvoiceRoute: DashboardAccountCreateInvoiceRoute,
  DashboardAccountInvoiceRoute: DashboardAccountInvoiceRoute,
  DashboardAccountSettingsRoute: DashboardAccountSettingsRoute,
  DashboardApplicationBlogRoute: DashboardApplicationBlogRoute,
  DashboardApplicationCalenderRoute: DashboardApplicationCalenderRoute,
  DashboardApplicationChatAppRoute: DashboardApplicationChatAppRoute,
  DashboardApplicationContactRoute: DashboardApplicationContactRoute,
  DashboardApplicationFileManagerRoute: DashboardApplicationFileManagerRoute,
  DashboardApplicationSocialAppRoute: DashboardApplicationSocialAppRoute,
  DashboardApplicationTodoRoute: DashboardApplicationTodoRoute,
  DashboardApplicationTourismRoute: DashboardApplicationTourismRoute,
  DashboardApplicationWeatherRoute: DashboardApplicationWeatherRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
