/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as MetricRouteImport } from './routes/metric'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationTodoRouteImport } from './routes/application/todo'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricRoute = MetricRouteImport.update({
  id: '/metric',
  path: '/metric',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationTodoRoute = ApplicationTodoRouteImport.update({
  id: '/application/todo',
  path: '/application/todo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRoute
  '/domain': typeof DomainRoute
  '/metric': typeof MetricRoute
  '/security': typeof SecurityRoute
  '/application/todo': typeof ApplicationTodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRoute
  '/domain': typeof DomainRoute
  '/metric': typeof MetricRoute
  '/security': typeof SecurityRoute
  '/application/todo': typeof ApplicationTodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRoute
  '/domain': typeof DomainRoute
  '/metric': typeof MetricRoute
  '/security': typeof SecurityRoute
  '/application/todo': typeof ApplicationTodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/databases'
    | '/domain'
    | '/metric'
    | '/security'
    | '/application/todo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/databases'
    | '/domain'
    | '/metric'
    | '/security'
    | '/application/todo'
  id:
    | '__root__'
    | '/'
    | '/databases'
    | '/domain'
    | '/metric'
    | '/security'
    | '/application/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabasesRoute: typeof DatabasesRoute
  DomainRoute: typeof DomainRoute
  MetricRoute: typeof MetricRoute
  SecurityRoute: typeof SecurityRoute
  ApplicationTodoRoute: typeof ApplicationTodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metric': {
      id: '/metric'
      path: '/metric'
      fullPath: '/metric'
      preLoaderRoute: typeof MetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/todo': {
      id: '/application/todo'
      path: '/application/todo'
      fullPath: '/application/todo'
      preLoaderRoute: typeof ApplicationTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabasesRoute: DatabasesRoute,
  DomainRoute: DomainRoute,
  MetricRoute: MetricRoute,
  SecurityRoute: SecurityRoute,
  ApplicationTodoRoute: ApplicationTodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
